### ISSUE TITLE
Fix vertical centering and margining issue on some content blocks of home page

### ISSUE THREAD

**Issue by mantagen** [dwyl/dwyl.github.io#101]
Seem to be conflicting styles on @hdrdavies  and @mantagen browsers.
Needs to be addressed.

**Comment by iteles** [comment]
Screenshots would be handy here so we can refer back to this if it happens again in the future!

**Comment by hdrdavies** [comment]
According to @mantagen we have already fixed this when we addressed  #104 and #105 so this was a duplicate. But next time we'll add screenshots. :+1:
