### ISSUE TITLE
Give section headings an absolute positioning 

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#102]

**Comment by iteles** [comment]
For something like this, you need to put in a one sentence explanation of why into the body of that first comment!

**Comment by hdrdavies** [comment]
Cool - will do next time!

**Comment by iteles** [comment]
Would still be good to know your reasoning...

**Comment by hdrdavies** [comment]
Right you are. We wanted them to be consistent with the links which were absolutely positioned at the bottom of each section. Also, the content is centered in the section, and we don't want the heading to be centered with it.

**Comment by iteles** [comment]
Understood :+1:
