### ISSUE TITLE
Give section boxes uniform heights

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#103]

**Comment by hdrdavies** [comment]
We couldn't quite figure this one out, so we'll come back to it (maybe). In any case, it still looks good as the only box which gets emphasised is the middle one due to more content in the box (in the 'Our Offering' section).

**Comment by iteles** [comment]
I'm not even particularly keen on this. A section should contain it's content and aside from a hero image there's no need for it really to be bigger than it needs to - that often leads to aesthetically displeasing results on bigger screens anyway. :+1:

**Comment by hdrdavies** [comment]
We're pretty much agreed on not doing it now too, but we felt on certain screen sizes the difference in heights of the boxes in the 'Our Offering' section sometimes didn't look how we wanted. The screen sizes were quite specific and weren't full screen desktop / mobile / tablet anyway. Happy to close this issue if you see fit. :smile:

**Comment by iteles** [comment]
Do you mean each section or specifically the 3 boxes in 'our offering'?

Screenshot might help me understand what you mean.

**Comment by hdrdavies** [comment]
Specifically the 3 boxes in 'Our Offering'

When the screen gets smaller:

![image](https://cloud.githubusercontent.com/assets/13098199/12952630/0195a020-d00f-11e5-8b05-071ad88b170b.png)

and even smaller:

![image](https://cloud.githubusercontent.com/assets/13098199/12952643/0b74d9c6-d00f-11e5-8c59-ba1a2daa88c2.png)

On mobile, the boxes go on top of each other so it won't be a problem there.
