### ISSUE TITLE
Make Splash section fully responsive

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#108]
We'll likely just have 'dwyl' below the heart rather than 'dwyl is a community of people' in the interest of space.

**Comment by iteles** [comment]
By the way 'dwyl is a community of people' by itself doesn't make much sense. I would use the whole tagline 'dwyl is a community of people using technology to solve real problems'

**Comment by hdrdavies** [comment]
In our stand-up we concluded we should discuss here #112 :+1:

**Comment by hdrdavies** [comment]
@iteles still want the 'people' to highlight in teal? 

![screen shot 2016-02-11 at 12 27 27](https://cloud.githubusercontent.com/assets/13098199/12976292/ddf08a7a-d0ba-11e5-8fe8-22feef7edca3.png)

**Comment by iteles** [comment]
I would highlight 'technology' and 'community' if we go with this tagline

**Comment by nelsonic** [comment]
Agree. especially if we have a brief section detailing what technology we use...

**Comment by hdrdavies** [comment]
In #119 one of our users suggested 'community' almost sounds like there's a lack of leadership - and suggested 'team' instead. Thoughts? 

Personally I like 'community' but I like the sound of 'team' too.

**Comment by iteles** [comment]
Let's go with 'team' for now. We can change it back if we think it's too 'not us'
