### ISSUE TITLE
Navigation | Doesn't make sense with scroll usage

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#115]
I understand the reasoning around having the 'Our Process' etc nav at the bottom of _each section_ and it makes some sense if I'm clicking between them. But if I'm scrolling (which is my and many people's default pattern when I get to a website), I don't think it works - it just looks unnatural and doesn't make sense when you get to this situation (wait, is that the end of the site? No? There's more? But wait...):
<img width="1778" alt="screen shot 2016-02-10 at 23 00 47" src="https://cloud.githubusercontent.com/assets/4185328/12964843/39868cc0-d04a-11e5-8aba-8cd7bf708421.png">

**Comment by hdrdavies** [comment]
We went for this look as we felt it would make it easier for users to cover this page instead of having to scroll loads - seeing as each section is full-screen height. However if it makes more sense to just allow for scrolling then I'm happy with that.

**Comment by mantagen** [comment]
@iteles @hdrdavies This seems like the perfect time for some user testing. Any objections to putting this link (https://dwylio-test.herokuapp.com/values) in FSC gitter channels and asking for UX feedback?

**Comment by hdrdavies** [comment]
Alternatively- we could have the scroll links on just the splash section and not have them on the others

**Comment by mantagen** [comment]
Agreed @hdrdavies 

Also an option would be to include the (currently two, eventually three) 'scroll-links' in the main nav-bar, and be done with all these links in content blocks.

**Comment by iteles** [comment]
@mantagen agree! But I think it needs to be in-person user testing so you can be listening to the feedback as it comes into the users' minds 👍🏻

**Comment by iteles** [comment]
As per #119, let's get rid of these and put them in the top nav
