### ISSUE TITLE
Contact form alignment

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#116]
A minor point, but the contact form doesn't have enough margin to the right and looks unbalanced, like someone pushed it across the page :wink: 
<img width="1659" alt="screen shot 2016-02-10 at 23 19 48" src="https://cloud.githubusercontent.com/assets/4185328/12965402/d0fdc386-d04d-11e5-9464-50254a5ceec7.png">

**Comment by mantagen** [comment]
Hmm, I see your point @iteles , I think this is really only an issue on screens with very high pixel width (mobile first! :wink: ). The idea on laptop/desktop is that the text to the left takes up half the width, and that the form takes up half the width.
I think this works well on large screens:
![image](https://cloud.githubusercontent.com/assets/12934669/12973752/a6eabfaa-d0a6-11e5-8b47-e22b3fd1133b.png)

However on XL screens perhaps we should consider another option. Perhaps setting a max-width on container for that section would be good.
It would then look something like this:
![image](https://cloud.githubusercontent.com/assets/12934669/12973804/261a2bf8-d0a7-11e5-9c14-f8dce3f3b23a.png)

**Comment by iteles** [comment]
I like the idea a lot! I just think that there isn't enough white space to the right of the contact form so it looks pushed up against that side. A small amount of extra margin would do the trick and make it look like it has breathing room (this is actually also relevant to the offering boxes)

**Comment by iteles** [comment]
Please comment out the non-existent phone number in the code for the first iteration.

**Comment by iteles** [comment]
Also... this is actually part of a bigger problem which is there isn't enough margin on the whole website - other sections feel just way too close to the edges of the browser:
<img width="1666" alt="screen shot 2016-02-15 at 00 57 47" src="https://cloud.githubusercontent.com/assets/4185328/13037738/6d6f599e-d37f-11e5-9e81-35414c4e7cda.png">

Rather than changing the contact box, the whole body below the nav just needs a small nudge (could be as small as 1em, not sure) of additional margin so it feels comfortable and not like it's close to falling off the page!

**Comment by hdrdavies** [comment]
Agreed! :+1:
