### ISSUE TITLE
Corners are too round on  section-box

### ISSUE THREAD

**Issue by mantagen** [dwyl/dwyl.github.io#118]
Work out the optimal border-radius for section-box.

Currently this:
![image](https://cloud.githubusercontent.com/assets/12934669/12973555/1e17ed16-d0a5-11e5-9ea1-d4c3aa2384ac.png)

I quite like these two:
border-radius: 12px;
![image](https://cloud.githubusercontent.com/assets/12934669/12973571/39e621c0-d0a5-11e5-8110-55d9b13fa28d.png)

border-radius: 5px; (probably my fave)
![image](https://cloud.githubusercontent.com/assets/12934669/12973590/59e19a36-d0a5-11e5-87ea-7295f651fb52.png)

**Comment by hdrdavies** [comment]
thanks for adding this issue - as per comment in #96 

I like both 12px and 5px

**Comment by iteles** [comment]
How about percentage values?

**Comment by mantagen** [comment]
I think percentage values on border radius are good when you want a specific shape eg circle, however I feel that if we want a consistent look across the site then px or em would be more appropriate.

**Comment by iteles** [comment]
Additional changes made: https://github.com/dwyl/dwyl.github.io/commit/015cbeca316e841c935a82be4efc8688e3a9864c
