### ISSUE TITLE
DNS Error

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#12]
![dwyl io-dns-error](https://cloud.githubusercontent.com/assets/194400/8120298/770a9d4a-1095-11e5-83de-4b3424b06a98.png)

http://dwyl.io/

I still cannot access the site...

**Comment by iteles** [comment]
AH, that's because for now it needs a www. infront of it. 
I have to figure out how to configure the A record on the DNS (it's on my list of to-dos for tomorrow) for a URL or figure out the IP address of our github.io page if it's accessible.

**Comment by nelsonic** [comment]
![noooo...](http://cdn.meme.am/instances/400x/56651426.jpg)

https://www.youtube.com/watch?v=FshkO8HqQ10

**Comment by iteles** [comment]
Useful, thanks.

**Comment by iteles** [comment]
Could you please try it again? Working on Safari, FF and Chrome on my computer.

**Comment by nelsonic** [comment]
I'm *really not a fan* of the **www.** (never have been...)
But yeah, it works. thanks.

**Comment by iteles** [comment]
Agreed, that was the default and I only realised that yesterday!
