### ISSUE TITLE
Source icon and change icon in 'Product development' to one with a desktop too

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#133]
Currently it's this:

![img](https://cloud.githubusercontent.com/assets/13098199/12919679/2ee1b186-cf3d-11e5-81b3-224c5c7faba6.png)

Myself and @iteles suggested it might help if it was a desktop *and* a mobile, as per #132

**Comment by iteles** [comment]
Really like the new one!

**Comment by hdrdavies** [comment]
:+1:
