### ISSUE TITLE
Bottom-line under header-nav cuts off half way

### ISSUE THREAD

**Issue by heron2014** [dwyl/dwyl.github.io#137]
Please navigate to contact or team to spot it:  

![line](https://cloud.githubusercontent.com/assets/8476884/13112967/e1eb95ec-d584-11e5-8171-ad65b7341d17.png)

**Comment by hdrdavies** [comment]
Took me less than 15mins

**Comment by iteles** [comment]
I still see the issue on Chrome on a Mac:
<img width="687" alt="screen shot 2016-02-17 at 20 31 26" src="https://cloud.githubusercontent.com/assets/4185328/13123729/85d6fd38-d5b5-11e5-946e-251d5628ecff.png">

**Comment by hdrdavies** [comment]
Only just seen this. Will try to fix now.
