### ISSUE TITLE
Adjust tagline in Our Offering

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#138]
![image](https://cloud.githubusercontent.com/assets/13098199/13115259/f838a1e6-d58e-11e5-9d5d-55734ee32565.png)

Our Offering tagline needs to be lower down

**Comment by hdrdavies** [comment]
Forgot to take the in-progress label off! But there's still a problem with this....

![screen shot 2016-02-18 at 12 02 12](https://cloud.githubusercontent.com/assets/13098199/13142816/99afcc04-d637-11e5-8eba-0a17c22ccbd7.png)

**Comment by iteles** [comment]
@hdrdavies Always good practice to add a screenshot of the fix here as well :+1:

**Comment by hdrdavies** [comment]
:+1: 

![screen shot 2016-02-18 at 12 12 25](https://cloud.githubusercontent.com/assets/13098199/13143165/fe903cf6-d639-11e5-9181-eda06c6954d3.png)
