### ISSUE TITLE
Sort hero image bug on mobile

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#141]
On iPhone 6 & iPhone 5, the hero image is appearing oddly... I am unsure why. 

![img](https://files.gitter.im/iteles/ZjYW/IMG_7949.PNG)

**Comment by mantagen** [comment]
@iteles Just wondering if you have any browsers other than safari on your iphone which you could check it on too?
Thanks!

**Comment by iteles** [comment]
Chrome on iPhone 6:

![img_7956](https://cloud.githubusercontent.com/assets/4185328/13353454/6baad21c-dc8c-11e5-9e24-5ec9cc3edf74.PNG)

**Comment by iteles** [comment]
Still hoping this will get fixed soon!

**Comment by hdrdavies** [comment]
@mantagen thought you'd solved this?

**Comment by mantagen** [comment]
@hdrdavies  Sorry it slipped by the wayside.
@iteles Could you verify that this is fixed. I've checked it on iphone with safari, could you please check with chrome?

**Comment by iteles** [comment]
@mantagen have you pushed this to the test heroku site? I can't tell because it's not in a PR :)

**Comment by mantagen** [comment]
@iteles Oops! I have now :)
