### ISSUE TITLE
~1mb way too big for splash image (same image loads on device - smaller devices should load smaller image)

### ISSUE THREAD

**Issue by mantagen** [dwyl/dwyl.github.io#142]

**Comment by nelsonic** [comment]
@mantagen suspect its because we are using an un-optimised image...

**Comment by iteles** [comment]
@nelsonic This is linked to PR #96

**Comment by iteles** [comment]
Thanks @mantagen ! https://github.com/dwyl/dwyl.github.io/commit/b3f4c404c2f7104675420f65651a8678857f408b
