### ISSUE TITLE
Add link to footer of website

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#146]
We should *clearly* state our support for http://www.chagossupport.org.uk/ by linking to them in our footer.

**Comment by iteles** [comment]
:+1: Couldn't agree more.

**Comment by iteles** [comment]
ba4fd6f

<img width="698" alt="screen shot 2016-05-02 at 18 55 18" src="https://cloud.githubusercontent.com/assets/4185328/14962579/7759bdd2-1097-11e6-81cc-7842b531633a.png">

**Comment by nelsonic** [comment]
Maybe it would be good to clarify *why* we support the Chagossians... i.e. .io domain...

**Comment by iteles** [comment]
I know, but in the footer? I'm considering it.

**Comment by nelsonic** [comment]
The *alt* is to *switch* to using the .co domain ... which we *should* do at some point...

**Comment by iteles** [comment]
I've thought about that as 'true' support but `.io` is way less 'amateur' than `.co`... linked to #32 .
