### ISSUE TITLE
Add roles to team page

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#147]
As a visitor to the site I would like to know what people's roles are within dwyl.

**Comment by iteles** [comment]
@nelsonic Any preference for your role?
Co-founder & Technical Lead?
<img width="1238" alt="screen shot 2016-04-09 at 06 35 14" src="https://cloud.githubusercontent.com/assets/4185328/14401987/47da0260-fe1d-11e5-997b-b2c7b8d658fe.png">

**Comment by iteles** [comment]
@nelsonic Any thoughts on this?

**Comment by nelsonic** [comment]
@iteles yes. can i merge?
