### ISSUE TITLE
icon design suggestion

### ISSUE THREAD

**Issue by Jbarget** [dwyl/dwyl.github.io#150]
Just a suggestion to move the icons above the titles

![screen shot 2016-03-28 at 11 59 51](https://cloud.githubusercontent.com/assets/11725595/14118813/14ff8898-f5e3-11e5-966f-2bbc924e444e.png)

**Comment by nelsonic** [comment]
PR it! :wink:

**Comment by Jbarget** [comment]
only a suggestion so might not be what everyone wants :)  but will create a PR for you guys to see what it looks like

**Comment by Jbarget** [comment]
minimum height of section-box needs adjusting to account for "Simplicity" 

![screen shot 2016-04-01 at 23 16 08](https://cloud.githubusercontent.com/assets/11725595/14221591/cd4ae842-f85f-11e5-9db5-57ee7ba5143c.png)

**Comment by Jbarget** [comment]
This is the final product in the PR, if you prefer the icons on the same line, seriously dont worry about not merging it in :) 

![screen shot 2016-04-01 at 23 20 58](https://cloud.githubusercontent.com/assets/11725595/14221664/6e58eb62-f860-11e5-957c-a40ae70a512f.png)
