### ISSUE TITLE
Missing Faces ... Marie? Justen? Harry?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#152]
There appear to be a *few* missing faces from this page... http://www.dwyl.io/team
@mk4111 @Jbarget @harrygfox ... https://www.youtube.com/watch?v=f5qICl3Fr3w ?

**Comment by harrygfox** [comment]
@nelsonic but what is to be done!?

**Comment by nelsonic** [comment]
@harrygfox please add yourself to this page and PR: https://github.com/dwyl/dwyl.github.io/blob/master/views/team.html

**Comment by tunnckoCore** [comment]
hey, the team page looks good :+1:

**Comment by mk4111** [comment]
@nelsonic should I also follow the same instructions that you gave to @harrygfox ?

**Comment by nelsonic** [comment]
@mk4111 please, if you have time. :-)

**Comment by iteles** [comment]
Thanks @SimonLab ❤️
