### ISSUE TITLE
Hero image is taking upwards of 7 seconds to load

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#156]
Both on desktop and mobile with _good_ internet connections.

Give the text ontop of the image is white, visitors are faced with a blank page that they can't interact with for 7 seconds+.

Linked to #142

**Comment by nelsonic** [comment]
whaaaat....? :confused:

**Comment by iteles** [comment]
yep

**Comment by nelsonic** [comment]
but isn't this the *new* image...?

**Comment by iteles** [comment]
Yep.

**Comment by iteles** [comment]
Much better!
