### ISSUE TITLE
serving everything from root

### ISSUE THREAD

**Issue by des-des** [dwyl/dwyl.github.io#157]
obvs not really a problem currently as repo is public anyway but thought I would point it out: http://www.dwyl.io/server.js.
https://github.com/dwyl/dwyl.github.io/blob/master/routes.js#L9
ie www.dwyl.io/.env does not give me anything but ..

**Comment by nelsonic** [comment]
@des-des good point. however we *always* set environment variables *manually* in Heroku as per: https://github.com/dwyl/learn-environment-variables#environment-variables-on-heroku and *exclude* them from GitHub in our `.gitignore` so the danger of exposing keys is *minimised*... 😉 

Do you have a suggestion for how we could *further* avoid the *stupid mistake* issue...?

**Comment by des-des** [comment]
@nelsonic I do not think it is a case of what is in the .gitignore. Since this repo is public I think we can trust people not push sensitive information up, and if they do, it does not matter if the server exposes this data, as it will already be publicly available on gh. The problem is that somewhere down the line, someone (misinformed) could end up saving sensitive information to the filesystem on whatever hosting service the site is on 
`fs.writeFile(path.join(__dirname, 'superSecretFolder/{userid}.json)', superSecretData)`
, assuming that, since they have not gone through the effort of making an endpoint to expose this folder to serve this data, it is safe in the server.
I guess this might be an overly contrived example ... I just think that something like keeping everything that is public in a folder called public is a nice way to keep clear the distinction between the site the the server.

**Comment by nelsonic** [comment]
Yeah, I *agree*! a `/public` folder is a *much* better idea than serving root. 👍 
If you have 🕥  to submit a PR, please do. 🐰

**Comment by iteles** [comment]
Resolved with https://github.com/dwyl/dwyl.github.io/pull/158, thanks @des-des! 🎩
