### ISSUE TITLE
Can we use Handlebars?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwyl.github.io#165]
the [team page](https://github.com/dwyl/dwyl.github.io/blob/master/views/team.html) could use a Handlebars partial to abstract the code of a profile. It will also make it easier to reorder the list of profile and to modify it.  Are there any reasons to not use Handlebars?

**Comment by iteles** [comment]
A good question for @mantagen and @hdrdavies who built it in the first place 😊  Any thoughts gentlemen?

(I think that would be a great idea)

**Comment by mantagen** [comment]
I can't think of a reason not to use it, given the context

**Comment by hdrdavies** [comment]
looks really nice @SimonLab
