### ISSUE TITLE
w3c validator error

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwyl.github.io#167]
Error on the main page:

![w3cerror](https://cloud.githubusercontent.com/assets/6057298/15386230/8c2801ce-1d9e-11e6-8d39-b176f11c401e.png)

Error on the value page:
![errordoctype](https://cloud.githubusercontent.com/assets/6057298/15386667/0afca980-1da1-11e6-8247-29448dfb03d1.png)

**Comment by nelsonic** [comment]
Well spotted. lets fix that.

**Comment by iteles** [comment]
This makes me saaaaaaaaaaaad!

**Comment by SimonLab** [comment]
Adding "size=5" on the select will resolve the first error but then the display of the dropdown is broken:
![size5](https://cloud.githubusercontent.com/assets/6057298/15390976/ab4dff78-1db6-11e6-8ff1-acd84b3ae746.png)

Another solution is to add a placeholder option with an empty value:
```<option value="">Estimation</option>```
This solution resolve the w3c error. The users won't be able to select this option because of the require attribute on the select:
![estimation](https://cloud.githubusercontent.com/assets/6057298/15391176/a6aec49c-1db7-11e6-8022-c8ffda592b85.png)

I also choose the text "Estimation" for the placeholder because "budget" wasn't display properly, I think   it needs some css change for that but I don't want to break everything:

![budget](https://cloud.githubusercontent.com/assets/6057298/15391267/245c3f8c-1db8-11e6-808e-199fefd28ace.png)


@iteles @nelsonic @mantagen @hdrdavies   what are your thoughts on this is the placeholder "Estimation" ok or should we find another solution?

The second error is resolved by just deleting the doctype in the partial index.html (there is already a doctype on the may layout)

**Comment by SimonLab** [comment]
I've overcomplicated things, just need to delete require on the select and select by default the first option, like this we avoid adding a placeholder on the dropdown (which was feeling weird)

**Comment by SimonLab** [comment]
This issue has been resolved with #168
