### ISSUE TITLE
404 Jackum not found

### ISSUE THREAD

**Issue by shouston3** [dwyl/dwyl.github.io#188]
For some reason [jack M's](github.com/jmurphyweb) photo is not in the [team images directory](https://github.com/dwyl/dwyl.github.io/tree/master/public/img/common/team).

**Comment by nelsonic** [comment]
@shouston3 thanks for _fixing_ that! ✅ 
have you thought of adding _yourself_ to the list...? 😜 
![sam-not-found](https://cloud.githubusercontent.com/assets/194400/21597890/e8ac6fde-d149-11e6-90a3-26403f8900ca.png)

**Comment by nelsonic** [comment]
Just saw #187 ... perhaps a more _descriptive_ PR name...? 😜
