### ISSUE TITLE
Time to re-brand?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#34]
https://twitter.com/amreenaslam/status/637496610629513216 :confused: 
(I clicked on https://twitter.com/hashtag/dwyl and read the first few tweets ....)

**Comment by nelsonic** [comment]
*Phew*! the song is called "Do What You L***ike***" ... https://www.youtube.com/watch?v=YIoSLwolzBU
(*terrible song*. *even* ***worse*** *video* ... that was close!)

**Comment by iteles** [comment]
:laughing: Don't scare me like that!

**Comment by iteles** [comment]
[This](https://www.jacobinmag.com/2014/01/in-the-name-of-love/) was interesting though.
> There’s little doubt that “do what you love” (DWYL) is now the unofficial work mantra for our time. The problem is that it leads not to salvation, but to the devaluation of actual work, including the very work it pretends to elevate — and more importantly, the dehumanization of the vast majority of laborers.
