### ISSUE TITLE
Your connection is not private - can you replicate this?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#39]
visit: https://www.dwyl.io/images/favicon.ico
tell me what you see.
<img width="901" alt="dwyl-favicon-not-private" src="https://cloud.githubusercontent.com/assets/194400/10196052/bcdab41e-6788-11e5-9b32-0bd6dd8255ef.png">

**Comment by iteles** [comment]
On iOS 9 safari I see a favicon.

**Comment by nelsonic** [comment]
Right, I was aksking if in *any* of your browsers/emulators you can see the error. but not to worry.
we can close this and if it gets reported by a person "*using*" our app we can re-open. thanks. :+1:
