### ISSUE TITLE
dwyl logo on white background

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#4]
Our logo looks way better on coloured background than on a white background. Need to look at the options for what it could look like on white.

**Comment by nelsonic** [comment]
agreed. are you on the case? :blush:

**Comment by iteles** [comment]
Of course.

**Comment by iteles** [comment]
![dwyl-logo-grey-heartoutline-notagline](https://cloud.githubusercontent.com/assets/4185328/8055445/93f3d5a2-0e97-11e5-9693-42a86b335cca.png)
![dwyl-logo-grey-heartoutline-tagline](https://cloud.githubusercontent.com/assets/4185328/8055447/93f86c34-0e97-11e5-87c6-f7141034eb40.png)
![dwyl-logo-grey-solidheart-notagline](https://cloud.githubusercontent.com/assets/4185328/8055446/93f6adcc-0e97-11e5-8505-70fe76dbb8a1.png)
![dwyl-logo-grey-solidheart-tagline](https://cloud.githubusercontent.com/assets/4185328/8055448/93f9ce6c-0e97-11e5-8241-d3d32695117b.png)
![dwyl-logo-pure-white](https://cloud.githubusercontent.com/assets/4185328/8055449/93fac240-0e97-11e5-81c3-3d54cd2c15ef.png)
![dwyl-logo-white-greyoutline-notagline png](https://cloud.githubusercontent.com/assets/4185328/8055450/93fce39a-0e97-11e5-80df-a16da1e7d1cf.png)
![dwyl-logo-white-greyoutline-tagline](https://cloud.githubusercontent.com/assets/4185328/8055452/940c6e5a-0e97-11e5-8616-8b7ca3b528ed.png)
![dwyl-logo-whitel-greyoutline-notagline](https://cloud.githubusercontent.com/assets/4185328/8055451/940c6ed2-0e97-11e5-8156-43b9e697e2f0.png)
![dwyl-logo-whitel-greyoutline-tagline](https://cloud.githubusercontent.com/assets/4185328/8055453/94103972-0e97-11e5-8848-37f2d0f8312b.png)
