### ISSUE TITLE
Responsiveness Enhancements Needed

### ISSUE THREAD

**Issue by enociz** [dwyl/dwyl.github.io#40]
As seen on [a screenplay preview of the site on mobile](http://quirktools.com/screenfly/#u=http%3A//www.dwyl.io&w=320&h=1700), the site doesn't exactly look _good_ in its current state for responsiveness.

I think simply making the site more responsiveness through the utilisation of media queries for the header and hero/signup area should do as the rest of the site looks pretty fine.

**Comment by nelsonic** [comment]
@enociz thanks for the feedback and link.
when we tested the site on a handful of devices it looked "*okay*" ... but we *definately* need a more systematic way of testing the responsiveness. http://quirktools.com/screenfly/ seems *really useful* ...
p.s. welcome to [***dwyl***](https://github.com/dwyl)

**Comment by enociz** [comment]
😉 thank you very much for the invite

**Comment by iteles** [comment]
@enociz Echoing @nelsonic's thanks for the screenfly link and also for spotting this! This is very much a temporary landing page (I think saying it looks 'fine' is maybe generous :wink:), the cogs are turning for something that is more descriptive and better looking as we speak.

 I've been playing with screenfly a little with it this morning and found some interesting quirks, such as the disconnect between what it _thinks_ an iPhone 6 screen would look like:
<img width="431" alt="screenfly-iphone6-dwylio-site" src="https://cloud.githubusercontent.com/assets/4185328/10218493/fe3cdcc4-682e-11e5-8df8-0010d3603f2b.png">

and what it _actually_ looks like on an iPhone 6:
![actual-iphone6-dwylio-site](https://cloud.githubusercontent.com/assets/4185328/10218509/16973a08-682f-11e5-8d97-959d771f9300.jpg)

But will keep investigating it :+1: 

Thanks again!

**Comment by enociz** [comment]
Screw fly has worked for me so far in the past but yeah, as any other responsiveness testing, it can definitely have flaws.

Maybe @dwyl should make an application for it that solves this and makes it easier? 😉

**Comment by iteles** [comment]
@enociz I like the way you think! :wink:

**Comment by enociz** [comment]
Hmm, I managed to whip out my lil' old iPhone 3G and it looks fine - must be a huge bug in screen fly. (Will add pic when I get time.)

Anyway, I guess this could just be turned into a revamp for the site.

**Comment by nelsonic** [comment]
Sweet! our iPhone 3G (testing device) died ... we should get another at some point.
Thanks again. We *always* love it when people spot visual issues.
