### ISSUE TITLE
Move away from github pages 

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#46]
So we can create new routes quickly and easily, but still _not_ use a _framework_.

e.g. `/websummit`

**Comment by nelsonic** [comment]
So... I don't think we *need* to move away from GHPages *before* WebSummit...
We "*just*" need to add the desired page ...

**Comment by nelsonic** [comment]
![_20151101_214429](https://cloud.githubusercontent.com/assets/194400/10871535/f026b274-80e1-11e5-83bd-d4a8c767ba46.JPG)

**Comment by nelsonic** [comment]
So are we deploying this to Heroku then...?

**Comment by iteles** [comment]
Heroku is probably our fastest/most reliable option in the short term (pre-websummit). We should open an issue on finding a more permanent hosting solution.

**Comment by nelsonic** [comment]
I'm on it! https://github.com/dwyl/dwyl.github.io/pull/56

**Comment by nelsonic** [comment]
@iteles see: https://dwylio.herokuapp.com/

**Comment by iteles** [comment]
Thank you for putting this on heroku! :+1: :blush:

Shall we debug together?

**Comment by iteles** [comment]
Ah, think I've found why the stylesheets aren't loading:
<img width="1540" alt="screen shot 2015-11-02 at 21 15 08" src="https://cloud.githubusercontent.com/assets/4185328/10894506/e6bb8172-81a6-11e5-84d8-9235e7a8ba90.png">

**Comment by iteles** [comment]
@nelsonic 
We can try using: https://cdnjs.cloudflare.com/ajax/libs/pure/0.6.0/pure-min.css and https://cdnjs.cloudflare.com/ajax/libs/pure/0.6.0/grids-responsive-min.css and https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css

**Comment by iteles** [comment]
:tada: Worked perfectly, thank you!

Looks like I have a really fun bug to fix now #59.

We can close this though, I repointed the DNS for `www` and it's working now. THANK YOU!
<img width="944" alt="screen shot 2015-11-02 at 21 43 44" src="https://cloud.githubusercontent.com/assets/4185328/10895226/ff30803c-81aa-11e5-8c80-640a23988679.png">

<img width="1106" alt="screen shot 2015-11-02 at 21 44 35" src="https://cloud.githubusercontent.com/assets/4185328/10895225/ff300774-81aa-11e5-90ab-845a34fd29a6.png">
