### ISSUE TITLE
Welcome variation | About us image isn't great and doesn't work above 1366x768 px

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#50]
Might not be _too_ much of an issue in terms of a CSS fix as I think we need to change this picture out pretty quickly. But the issue at the moment is as follows.

1366 x 768px:
<img width="714" alt="screen shot 2015-10-29 at 22 58 46" src="https://cloud.githubusercontent.com/assets/4185328/10834398/01a3ccba-7e91-11e5-8792-da349e505ec8.png">

1920 x 1080px, cuts off people's heads:
<img width="806" alt="screen shot 2015-10-29 at 22 59 03" src="https://cloud.githubusercontent.com/assets/4185328/10834397/fe49c2fe-7e90-11e5-8c92-dd1f75bea477.png">

**Comment by nelsonic** [comment]
We have a *betterer* image: https://github.com/dwyl/dwyl.github.io/issues/51#issuecomment-152860807 would you not agree...? :wink:

**Comment by iteles** [comment]
:+1: I originally used this one as a test image because it's long and thin - the one you mention doesn't lend itself as well to a thin pane of information which is what I had in mind at the time.

**Comment by nelsonic** [comment]
Sounds like you might have a *fun* task on your hands... https://github.com/dwyl/dwyl.github.io/issues/53

**Comment by iteles** [comment]
Now null and void given that we're completely changing the website ( #51 ) and #53 exists.
