### ISSUE TITLE
Complete overhaul of website

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#51]
There are a few issues with the website as it stands:
+ It doesn't make it clear what we do
+ The call to action is murky - what are people actually signing up for?
+ It isn't very captivating (you get a feeling of _meh_ when you see it)

<img width="1250" alt="20151101-dwylio-website-screenshot" src="https://cloud.githubusercontent.com/assets/4185328/10870924/1b90f5ee-80d0-11e5-9854-9aa46472e6d6.png">

Given that we're at the [web summit](websummit.net) in the next couple of days, this should be our top priority at the moment.

**Comment by nelsonic** [comment]
*Agree* with your observations. the question is: ***Why*** is "*meh*"...?

**Comment by iteles** [comment]
In my opinion, it lacks personality. We try to infuse a lot of positivity and parts of ourselves into everything we do but at the website at the moment just feels generic. It doesn't say anything about the wonderful dwyl community of make it clear what dwyl actually does.

Visually, it also feels quite bland. It's mostly words on a page. A blog post on the subject of **the line between _'simple'_ and _'bland'_** would probably be very apt here.

## Aims:
+ Know exactly what our main goal is and craft the right [call to action](https://en.wikipedia.org/wiki/Call_to_action_(marketing)) for it
+ Clarify who we are and what we do in the copy
+ Tell our story in a better way - what makes us 'us'?
+ Make the visual design more appealing 
+ Create `/websummit` endpoint which is more personal to the websummit experience (this can be iterated on over the websummit as we experience it ourselves as well).

**Comment by nelsonic** [comment]
Do you have the [**#dwylsummer**](https://twitter.com/hashtag/dwylsummer?f=images&vertical=default&src=hash) photo of the all the people in the Pool Garden in High Res...?

**Comment by iteles** [comment]
This is my favourite photo of #dwylsummer part 2:
![dwylsummer-lx-garden-team-shot](https://cloud.githubusercontent.com/assets/4185328/10871060/2dd4b76e-80d4-11e5-9a7c-a43537b572c6.jpg)

**Comment by nelsonic** [comment]
Agree ***unequivocally***! Thanks for digging it out. :white_check_mark:

**Comment by nelsonic** [comment]
So... You know how we said we *weren't* going to use a CSS Library for the dwyl website...?
how about one that "*only*" takes **4kb** to do a responsive Landing Page with a contact form...?
http://purecss.io/layouts/marketing/

**Comment by nelsonic** [comment]
I'll see your photo upload and raise you a *cropped* version:
![dwylsummer-part2-team](https://cloud.githubusercontent.com/assets/194400/10871136/9bf97598-80d6-11e5-8da1-70fa14c919c0.jpg)

**Comment by iteles** [comment]
On PureCSS, totally agree: https://github.com/nelsonic/html-form-send-email-via-google-script-without-server/issues/4#issuecomment-149040429

**Comment by iteles** [comment]
I had a hard time finding a browser support table for pure, but instead found this:
> Pure is tested on IE7+, Latest Chrome, Safari, FF, iOS 6,7 and Android 4+.   
We make sure everything gracefully degrades in older browsers like Android 2.x and IE6.

https://github.com/yahoo/pure/issues/228#issuecomment-28357779

(which is good to know because they [certainly use flexbox](https://github.com/yahoo/pure/blob/master/src/grids/css/grids-core.css) which is unsupported in many browswers (pre-IE10: http://caniuse.com/#search=flexbox)

**Comment by iteles** [comment]
The websummit milestone portion of this is done with PR #56.

We should open a new issue for this post websummit.

**Comment by hdrdavies** [comment]
I'd **never seen** this page before, and I really like the message and introductory paragraph about how dwyl was born. A really strong call to action too. Hopefully we can reproduce this in the current iteration :+1: 

![image](https://cloud.githubusercontent.com/assets/13098199/12716285/258dc49c-c8d7-11e5-9ca2-e566630d0e32.png)

**Comment by iteles** [comment]
@hdrdavies This was in the days when were on our way to launching our time management product (before we took on external clients because of https://github.com/dwyl/ateam-proposal

**Comment by hdrdavies** [comment]
@iteles I thought so! It won't be quite the same message but the overall tone is interesting and does a good job of differentiating dwyl from the pack :+1:
