### ISSUE TITLE
Contact Form?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#52]
Do we want to have a contact form on our website...?

(*Hint: there is a* ***right answer*** *to this question...* :wink: )

**Comment by iteles** [comment]
Of course!

![spaceship](http://i.ytimg.com/vi/lz4PCZ6iRyA/maxresdefault.jpg)

**Comment by nelsonic** [comment]
Nah... Not a fan of building Spaceships. We're building ***Bicycles***!

![flat-simple-bicycle-hipster](https://cloud.githubusercontent.com/assets/194400/10871205/605b400a-80d8-11e5-993a-2df4b8d8e70a.jpg)

But *get* what you mean... :stuck_out_tongue_winking_eye: 
I like to think of what we're doing as more of a:

![double-decker-couche](http://images-cdn.moviepilot.com/images/c_fill,h_420,w_1000/t_mp_quality/y7oqy7pcpikbuclrxlkt/this-lucky-family-has-their-own-double-decker-couch-and-it-s-awesome-405756.jpg)

**Comment by iteles** [comment]
https://www.youtube.com/watch?v=SSUXXzN26zg

**Comment by nelsonic** [comment]
Try not to get distracted... we have 24h to get a ***LOT*** of works done... :wink:

**Comment by iteles** [comment]
Still need to turn the 'enter your email' box at the bottom of the page into a contact form... :hourglass_flowing_sand:

Do we want to have a link to contacting us from the navigation? I vote yes and that for now we loose the 'Who?' in favour of a 'Contact' (so we don't have to iron out a ton of bugs).

**Comment by iteles** [comment]
Done! In commit https://github.com/dwyl/dwyl.github.io/commit/daa815796d435fd7d14d780448128cb4fbd750f5.

Thanks @nelsonic :sunglasses:

**Comment by hdrdavies** [comment]
This issue is amazing

**Comment by nelsonic** [comment]
@hdrdavies lol. :wink:

**Comment by iteles** [comment]
😄👌🏻
