### ISSUE TITLE
Question Based Navigation?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#54]
I'm in favour of having a *Question Based* **Top Navigation**
# Why? | Who? | What? | How?
Relates to: https://github.com/iteles/ateam/issues/13#issue-109937767

**Comment by nelsonic** [comment]
We need to create the anchors for this and content/copy do you want to divide up the sections and we each work on a couple? @iteles

**Comment by iteles** [comment]
Yes. I have bug #59 to work on too which might be higher priority. What do you think?

**Comment by nelsonic** [comment]
Please work on *visual* regressions first. agreed.

**Comment by iteles** [comment]
:+1:

**Comment by iteles** [comment]
Works! We should A/B test this.
