### ISSUE TITLE
Diagram of MVP methodology

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#61]
<h1><a>How?</a></h1>
<p>
  We have a 3-step approach to getting your idea(s) tested
  in the hands of <em>real</em> people.
</p>
<ol>
  <li>
    <em>Understand</em> the problem that needs to be solved
    and ensure the intended users feel the <em>pain</em>
    and <em>need</em> for a solution.
  </li>
  <li>
    <em>Prototype</em> the solution and get feedback from
    <em>real</em> people as fast as possible.
  </li>
  <li>
    <em>Review</em> customer feedback and <em>confirm</em> we are
    making progress toward solving the problem.
    If
  </li>
</ol>

relates to: #60

**Comment by hdrdavies** [comment]
I like the way pebble code has captured some the process described above: 

![agiledevelopment](https://cloud.githubusercontent.com/assets/13098199/12717420/b494f702-c8df-11e5-9d73-0d50bfa0b6c0.png)

![testingmethodology](https://cloud.githubusercontent.com/assets/13098199/12717423/b7ea3f5c-c8df-11e5-9c27-20e4f3d2e902.png)

...though there isn't a *specific* prescription as to what their services are - their *Work* section covers this. I think our *Portfolio* section would do this well.

**Comment by hdrdavies** [comment]
To add to this, [youteam](http://youteam.co.uk/) have a interesting visualisation of their 'process', which we could draw from:

![process](https://cloud.githubusercontent.com/assets/13098199/12725298/f86fc6e4-c909-11e5-84c2-bfb21afb9fbb.png)

**Comment by nelsonic** [comment]
@hdrdavies have you come across *this* diagram: 

![mvp how to](https://pbs.twimg.com/media/By-5IvXCEAAMB4s.png)

**Comment by hdrdavies** [comment]
@nelsonic No actually! Big fan though :smile:

**Comment by iteles** [comment]
I need to fix the copy on this:

<img width="705" alt="screen shot 2016-02-10 at 23 15 10" src="https://cloud.githubusercontent.com/assets/4185328/12965184/2e0976d0-d04c-11e5-9949-73a83a78eb05.png">

We know **for sure** that way doesn't work and the diagram needs some explanation to an uninitiated audience.

**Comment by iteles** [comment]
Done in https://github.com/dwyl/dwyl.github.io/pull/160/commits/3158a6b92c9fc631dfee701c178c2d533eb47989

**Comment by iteles** [comment]
Closing for now as we need to open a new issue on improving this. We can refer back to this one for the `research`.
