### ISSUE TITLE
Anchors aren't working properly

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#63]
`Who?` defaults to the top of the page for now, and `#contact` works great, but the `What?` and `How?` anchors are shot, [possibly because of pure's padding](http://stackoverflow.com/questions/12842749/id-anchors-are-scrolling-slightly-too-far) which I haven't quite got to the bottom of yet. 

`What?` works fine on mobile, but on desktop:
<img width="1201" alt="screen shot 2015-11-04 at 04 02 10" src="https://cloud.githubusercontent.com/assets/4185328/10929252/17525fd8-82a9-11e5-83c9-8974cd0e58c1.png">

`How?` works terribly on mobile AND desktop:
<img width="286" alt="screen shot 2015-11-04 at 04 01 44" src="https://cloud.githubusercontent.com/assets/4185328/10929255/25e916a4-82a9-11e5-95a5-f1dccbb4ee18.png">
<img width="1204" alt="screen shot 2015-11-04 at 04 02 21" src="https://cloud.githubusercontent.com/assets/4185328/10929256/29d858f6-82a9-11e5-8ed3-6444ffa0078b.png">

**Comment by mantagen** [comment]
I just came on here to raise this as an issue too. Glad it's been flagged up already.
Am I good to fix this? Will I have the privileges?

**Comment by iteles** [comment]
@mantagen Granted! :sparkles: Please submit a PR and assign it to me :+1:
