### ISSUE TITLE
Intro text hard to read when covering people's in photo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#65]
![dwyl-intro-text-hard-to-read-when-covering-people](https://cloud.githubusercontent.com/assets/194400/10933711/7534dcec-82d2-11e5-9645-92fb12a5d203.png)

**Comment by iteles** [comment]
:+1: Agreed. Need to try thicker letters (tried all the colours last night and white was the best one, but ran out of time to bug fix with different `font-weight`s.

**Comment by nelsonic** [comment]
Right... *but*... what if you put the text *above* people's heads instead of covering their t-shirts...?

**Comment by iteles** [comment]
That's an actual nightmare with this template. We need to move away from it to something a little more customised in the navigation and splash section.

**Comment by nelsonic** [comment]
@iteles please take the ***Lead*** on this and find a "better" template.

**Comment by iteles** [comment]
Of course!

**Comment by nelsonic** [comment]
Please focus on getting *this* iteration done rather than *researching* for the *next* one...

**Comment by iteles** [comment]
I meant: As I'm researching how best to do things for _this_ iteration, I'm taking a note of anything promising for the _next_ one.

**Comment by nelsonic** [comment]
Right... but the deadline on the UI for this was yesterday... :cry:

**Comment by iteles** [comment]
As I [explained above](https://github.com/dwyl/dwyl.github.io/issues/65#issuecomment-153705080), I tried a number of things yesterday and I ran out of time to debug the font weight and placement changes before the updates went onto the site this morning. They were breaking the layout in a bad way, so I reverted to this version.

Thanks for opening the issue. It's on my list. 
<img width="762" alt="screen shot 2015-11-04 at 15 51 21" src="https://cloud.githubusercontent.com/assets/4185328/10943349/f1da9d16-830b-11e5-9587-76bbed5bdc45.png">
<img width="765" alt="screen shot 2015-11-04 at 15 50 59" src="https://cloud.githubusercontent.com/assets/4185328/10943354/f6a42402-830b-11e5-9541-9e37d69d6f51.png">

**Comment by hdrdavies** [comment]
What about a *transparent* box behind the text? The text will be easier to read and the image will remain viewable.

**Comment by iteles** [comment]
@hdrdavies We don't even have to go with this as a hero image anymore when we have our 'meet the team' page (remember the client who said "it looks like a bunch of kids having fun and not a company"), so let's see where your ideas take you - this might even become a non-issue :wink:

**Comment by hdrdavies** [comment]
@iteles good point - I like Nelson's idea of having short individual profiles with one headshot image. Might help get away from that 'kids' perception!

**Comment by iteles** [comment]
Fixed in the new website!
