### ISSUE TITLE
Can Sign up to receive updates button wording be improved?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#66]
![email-button-copy](https://cloud.githubusercontent.com/assets/194400/10934234/905888da-82d6-11e5-96fa-2e08e70fe689.png)

**Comment by nelsonic** [comment]
I *propose*:
![please-tell-me-more](https://cloud.githubusercontent.com/assets/194400/10934274/c90c2a38-82d6-11e5-8def-ec064f1b992b.png)

*thoughts* @iteles  ?

**Comment by iteles** [comment]
This is no longer an issue for now as we went with turning it into a contact form #52.
