### ISSUE TITLE
'Please tell me more' email isn't being sent

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#67]
At the moment, I'm getting a test email every time someone fills in their email address in the 'Contact' section, but no email from dwyl to me as the person who has just signed up.

Will this become redundant with #52 ?

This is why:
<img width="1220" alt="screen shot 2015-11-04 at 12 29 58" src="https://cloud.githubusercontent.com/assets/4185328/10938169/f3fe4122-82ef-11e5-8a06-65fe5c82959d.png">

**Comment by nelsonic** [comment]
@iteles do you know *where* the email addresses *were* being recorded?

**Comment by iteles** [comment]
@nelsonic THANK you :kissing_heart:
