### ISSUE TITLE
Change github.io URL to dwyl.io

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#7]
Currently if we use [Github Pages](https://pages.github.com/) to host the site for convenience (hooray MVP :tada:), but this posts to dwyl.github.io. We'll need to transfer this to the www.dwyl.io URL.

**Comment by iteles** [comment]
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by nelsonic** [comment]
sounds promising. :wink:

**Comment by iteles** [comment]
Done by adding CNAME file in commit [5b411efdd03e1db0fc496eb074ace9c0dd0c90c8](https://github.com/dwyl/dwyl.github.io/tree/5b411efdd03e1db0fc496eb074ace9c0dd0c90c8).
Added DNS record in domain provider:
![dwylio -added-ghpages-dns-record](https://cloud.githubusercontent.com/assets/4185328/8106187/1259ae08-1037-11e5-86c3-eb0db7f447cb.png)
