### ISSUE TITLE
Unable to Sign Up to Email

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#71]
@iteles you first noted this. did you create an issue for it?

When attempting to get more information on the dwyl website we are unable to register with an email:

<img width="1107" alt="dwyl-new-site-attempt-to-sign-up" src="https://cloud.githubusercontent.com/assets/194400/10993917/907a69f6-846a-11e5-8dff-d803e94ac0be.png">

Submission is blocked:

<img width="1107" alt="dwyl-new-site-cross-origin-issue" src="https://cloud.githubusercontent.com/assets/194400/10993922/97d5bcf0-846a-11e5-8c34-5c9f6974da09.png">

**Comment by iteles** [comment]
https://github.com/dwyl/dwyl.github.io/issues/67

**Comment by iteles** [comment]
Closed with commit https://github.com/dwyl/dwyl.github.io/commit/daa815796d435fd7d14d780448128cb4fbd750f5
