### ISSUE TITLE
Link to 'Contact Us' in navigation?

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#72]
Do we want to have a link to contacting us from the navigation?

Or do we want people to scroll through the content? It's not very long now, but this will become a need as there's more content.

**Comment by nelsonic** [comment]
Please feel free to add the anchor back in. :+1:

**Comment by iteles** [comment]
The anchor is still there, but we never had it as part of the navigation across the top. That's the real question:

Who?   What?   How?   Contact

**Comment by nelsonic** [comment]
Oh. no then. no top-nav required for contact.

**Comment by iteles** [comment]
Question answered :+1: We can A/B test this later.
