### ISSUE TITLE
Spelling of Mum/Mom

### ISSUE THREAD

**Issue by mantagen** [dwyl/dwyl.github.io#74]
Is the site targeted at a UK audience predominantly? If so, it might be worth considering changing the spelling to Mum on the contact form.

**Comment by sohilpandya** [comment]
+1 Don't want @mantagen to be alone on this issue. :smile:

**Comment by iteles** [comment]
:+1: On it. Thanks guys!

**Comment by nelsonic** [comment]
love that you spotted that @mantagen :wink: 
I'd say British people *tolerate* the spelling ... 
see: http://momtestbook.com/ (*written by @robfitz who is a fellow-Londoner...*)

**Comment by rub1e** [comment]
Speaking on behalf of all Brits, no, no we bloody do not tolerate that. He clearly called his book that so it would sell outside the UK - and he should be ashamed of himself

**Comment by rub1e** [comment]
Hang on...

> a fellow-Londoner

You mean an American living in London

**Comment by robftz** [comment]
I am indeed ashamed. I even have a compilation setting on the book project to replace all the "mums" with "moms". You guys could always switch to the more culturally neutral "mother dear".

**Comment by rub1e** [comment]
or _mater_ - it's a classic...

**Comment by nelsonic** [comment]
lol! Think this calls for a geo-location targeted front-end i18n filter to "*translate*" our page... :wink: 
> @robftz we :heart: your Book BTW!

**Comment by sohilpandya** [comment]
@nelsonic Could we see the analytics for the site? I've got a feeling most of our traffic will be from UK currently.

**Comment by nelsonic** [comment]
@sohilpandya (@mantagen) lol! analytics indeed. ask @iteles for access. :wink: 
Yes, most of the visitors to dwyl.io are from UK... *for now*...

**Comment by iteles** [comment]
Actually...

<img width="868" alt="screen shot 2015-12-04 at 13 39 57" src="https://cloud.githubusercontent.com/assets/4185328/11592592/5c6bee6c-9a97-11e5-8e7a-2ca06315e11d.png">

**Comment by iteles** [comment]
We need to improve the site so we can actually start pointing people to it...

**Comment by mantagen** [comment]
@iteles :astonished: 
However, I've seen statistics like that before. It would be good to see a breakdown, as many spam bots come from the states...
Also work considering click-through rates :wink:

**Comment by iteles** [comment]
No longer used.
