### ISSUE TITLE
Profile Pictures, Descriptions & Links

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#78]
@hdrdavies as per email ... soon, we need something like *this*:
http://liberty-x.github.io/#team
![huws-blog-people-profiles](https://cloud.githubusercontent.com/assets/194400/12339439/ffc055d6-bb0c-11e5-9e54-c825c6622389.png)

**Comment by tunnckoCore** [comment]
:+1:  
Btw, sorry that Im not so active in the org :)

**Comment by nelsonic** [comment]
@tunnckoCore you're busy, that's a *good* thing! :wink:

**Comment by tunnckoCore** [comment]
@nelsonic hahaha, yea! duh.. exams. 

Thanks for the understanding. :wink:

**Comment by iteles** [comment]
@tunnckoCore Good luck with the exams! :four_leaf_clover:

**Comment by hdrdavies** [comment]
awesome!

**Comment by hdrdavies** [comment]
Linked to #87

**Comment by iteles** [comment]
Done for now! Will need some more work to add descriptions.
