### ISSUE TITLE
Anchor Sections do not scroll to correct place

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl.github.io#84]
When I click on one of the links in the top nav e.g: 
*firstly* the links do not become `active` and *second* the page does not scroll to the expected point.
see:

![dwyl-website-anchors-dont-scroll-to-correct](https://cloud.githubusercontent.com/assets/194400/12557939/15ddcb16-c385-11e5-8b05-ab4ade8e4cb7.png)

**Comment by iteles** [comment]
Agreed. Duplicate of #63 .

**Comment by iteles** [comment]
Closed as a duplicate and there has been some commentary on #63 already
