### ISSUE TITLE
What is our offering?

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#86]
For this first iteration, we need to cover 3 main areas:
1. Product development (mobile-first MVPs)
2. User testing (customer development, user testing, product walkthroughs)
3. Training (React, Redux, TDD)

**Comment by iteles** [comment]
@hdrdavies This might help as a starting point for the website :wink:

**Comment by hdrdavies** [comment]
Thanks! :+1:

**Comment by iteles** [comment]
Training is mostly for devs or clients' in-house devs. The training we do as part of our projects for the client is separate: product owner and GH training.

**Comment by hdrdavies** [comment]
[tbc.digital](http://tbc.digital/) come up pretty high on google search for  'mvp development london', and in terms of pricing...

![pricing](https://cloud.githubusercontent.com/assets/13098199/12723718/7f315934-c902-11e5-8cf4-ddac56bda6b7.png)

http://tbc.digital/what-we-do/startups

**Comment by hdrdavies** [comment]
#96 holds the content for this, though we're looking to add graphics / diagrams to the left panel of the section

**Comment by hdrdavies** [comment]
Layout for offering section:

![offering](https://cloud.githubusercontent.com/assets/13098199/12918926/b81ff812-cf39-11e5-91ab-6d1c859d726b.png)

Planning on using the images found in #99, but will need to be credited somewhere like so:
Mile by shimaru, Student by Berkay Sargın, Smartphone by João Proença - all from the Noun Project!

**Comment by iteles** [comment]
The training offering isn't correct on #96. We offer full, robust training for companies. As part of projects we also always train our clients, but that's not our main offering.

My job to write the copy on this. Will get on it!

**Comment by iteles** [comment]
We've also lost the clarity of what we do. We need to remember that a lot of our audience will come across this site with just an idea and no clue about how technology projects work. We need to make them feel safe straight away.

<img width="1298" alt="screen shot 2016-02-10 at 23 07 25" src="https://cloud.githubusercontent.com/assets/4185328/12965016/2ed4a400-d04b-11e5-9e47-4430cceff54f.png">

**Comment by hdrdavies** [comment]
We could add some text above the current offering boxes to make a 'softer' intro? 

![img](https://files.gitter.im/hdrdavies/JustMe/zn4Y/box.png)

**Comment by iteles** [comment]
👍🏻

**Comment by hdrdavies** [comment]
@iteles Shall we put the first line of:

'We make digital products and services that people love using and test ideas as fast as possible"

in that space?

**Comment by iteles** [comment]
Sounds great!
