### ISSUE TITLE
Create endpoint to hide Mandrill API key

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#9]
Having our Mandril API key exposed to the world is a terrible way to do things. We need to create a Mandrill endpoint (on Heroku or Firebase?) to fix this and hook the functionality of sending an email into `index.html`. 
The form is already commented out in `index.html` (ID = #signup https://github.com/dwyl/dwyl.github.io/blob/master/index.html#L56) and will provide a single field so people visiting dwyl.io can enter their email address and have it sent to us.

**Comment by iteles** [comment]
@nelsonic Do you have the time to do this? :blush:

**Comment by nelsonic** [comment]
Please use this as an exercise in being *way* more precise with your requirements... Spell them out *exactly* as you want the functionality to work.

**Comment by iteles** [comment]
The required functionality is:
1. Person enters their email in form on dwyl landing page
2. Person clicks the accompanying button (text of button in A/B testing)
3. Person receives welcome email from us
4. Email address is added to our mandrill list

This will require:
+ [x] [Form in index.html](https://github.com/dwyl/dwyl.github.io/blob/master/index.html#L56) for entry of email 
+ [ ] Request to be sent to the server with email information
+ [ ] Passing of info to Mandril through (API key held as a secret environment variable, not exposed to the world as per the original aim of this issue)
+ [ ] Set up of welcome email to be sent via Mandril

**Comment by nelsonic** [comment]
How about: "*as a person interested in using dwyl...*"

**Comment by nelsonic** [comment]
@iteles try it:
```
curl --data "email=dwyl.smith+1234@gmail.com" https://dwylapi.herokuapp.com/email
```

**Comment by iteles** [comment]
Thanks! :tada:
