### ISSUE TITLE
Single page? Front page prototype

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#91]
While I like the idea of a single page that you can scroll down and view all the information, I feel we should separate some of what is on the page now into other pages (similar to where the blog will be found) - namely *values*. We can also have other pages for the *profiles* and *portfolio*.

I foresee a slick single page scroll down in this order:

-Landing page / hero image with short intro (we are dwyl, a community of people - link to who page(?))
-Our Offering #86 
-Our Process #61 (could be a diagram, or a short description in the interest of expedience)
-What our clients say #88 (with a picture from their linkedin / twitter)
-Contact form #55 (perhaps with added fields for extra info as well as a contact number)

**Comment by nelsonic** [comment]
@hdrdavies good question. we only did the single page because its the *simplest* thing we could do to get the site done for our deadline. but we would *love* to have *moar* pages of content ...

**Comment by iteles** [comment]
@hdrdavies totally agree. We should have our blog on a separate page too - is t worth having something on the homepage on our latest posts?

And Meet the Team may need its own home too

**Comment by iteles** [comment]
Had another look at this just now (with a little more time). This sounds like a _fantastic_ starting point (which triggers a lot of ideas), let's get it up by the end of the week! :tada:

**Comment by hdrdavies** [comment]
@iteles Yep! It'll have its own home - I called it *profiles* above, but should have called it *Meet the Team* to avoid confusion!
