### ISSUE TITLE
Top priorities for site content

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#92]
Based on #91 

The *main* priorities for this iteration would be 

-A landing page image which doesn't look *'like a bunch of kids'*
-A succinct few lines on our offering #86 
-A concise explanation (and possibly a diagram as in #61) of our process
-Feedback from a couple of clients (if possible) as per #88 
-A first blog post!
-A couple of short profiles #87 #78 
-A couple of portfolio pieces #58 

Assigning you @iteles as you asked for this earlier :smile:

**Comment by iteles** [comment]
I'm going to have a busy Wednesday 😄

**Comment by hdrdavies** [comment]
@iteles :wink:
