### ISSUE TITLE
Hero image

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#93]
What image do we want displayed when we land on the page? I don't *necessarily* think it should be one of people having fun etc. (we all know what this suggests to clients!)

I like the use of graphics as per:

![image](https://cloud.githubusercontent.com/assets/13098199/12779524/49393464-ca60-11e5-959c-ae47a2dea918.png)

What about a big dwyl heart and a short intro below it?

**Comment by iteles** [comment]
Agree. For this first iteration, I would go with something graphical and kind of muted. Happy to try whatever you think!

**Comment by hdrdavies** [comment]
@iteles :+1: ! Do you keep your dwyl graphics in a specific place?

**Comment by iteles** [comment]
@hdrdavies We should do, but actually we don't yet (though there's a bunch of stuff in the https://github.com/dwyl/print-me/ repo). I emailed some to you!

**Comment by hdrdavies** [comment]
Great! We're thinking of having a (professional-looking) background image with a transparent layer of grey. As per the image here (which is of course teal, not grey!):

![image](https://cloud.githubusercontent.com/assets/13098199/12813430/d7671aec-cb2f-11e5-9719-16fe5a343346.png)

So it ends up looking a little like this (but with the logo over the front): 

![reasonfactory](https://cloud.githubusercontent.com/assets/13098199/12813455/0d5e5bce-cb30-11e5-8da6-c1632d64c4ec.png)

**Comment by iteles** [comment]
Do it! We'll course correct if needed afterwards :)

**Comment by hdrdavies** [comment]
@iteles Have you got an .svg image of your heart logo?

In the assets we'll be using pngs - but we'd like to edit the images.

Thanks!

**Comment by iteles** [comment]
I'll email you the SVGs I have!

**Comment by hdrdavies** [comment]
Completed in #96, but we may use another tagline

**Comment by iteles** [comment]
Adding another idea here: https://novoed.com/

A nice wooden table with laptops open, a plant in the middle, a few cups of tea, wireframes on the table and various hands coding away (from our actual dwyl team!). We could maybe look to take a photo like this at the next dwylhq lunch https://github.com/dwyl/hq/issues/89 if we think it's a good idea :+1: 
<img width="1631" alt="idea-for-dwylio-her-image" src="https://cloud.githubusercontent.com/assets/4185328/12869990/95897724-cd27-11e5-8b03-471b6fe304e2.png">

**Comment by nelsonic** [comment]
@iteles :heart: the idea! 
(do you want to create a *new* issue for this...?)

**Comment by iteles** [comment]
#97

**Comment by iteles** [comment]
So our landing page currently looks like this:
<img width="1778" alt="screen shot 2016-02-10 at 22 48 30" src="https://cloud.githubusercontent.com/assets/4185328/12964535/961b257e-d048-11e5-8f2f-e83af1ecf035.png">

And it needs something to give it interest. It just look a little too void of personality!

**Comment by hdrdavies** [comment]
Agree that it needs to look less bleak. I would say we might not want to use the one before so we don't look too *kidsy*... I would say a great photo from dwyl brunch from @sohilpandya would be the ideal, but in the meantime we could have a stock photo like the below (I didn't go for the many photos with the suited look):

![image](https://cloud.githubusercontent.com/assets/13098199/12965093/a1a1672a-d04b-11e5-8e24-93f56e002c0c.png)

(which is kept  [here](https://unsplash.com/photos/_aNFQ_7RxNc))

**Comment by iteles** [comment]
A version of this with more than a loner would work :+1:

**Comment by iteles** [comment]
OR we just go out to recharge (who have nice tables) near us with a few people on Friday and ask @sohilpandya nicely to take a photo!

**Comment by sohilpandya** [comment]
WeWork is also a very nice place to do photography. Maybe we all go there for a day?

**Comment by iteles** [comment]
@sohilpandya This is a little more urgent than that ;)

**Comment by sohilpandya** [comment]
I'm sure as an alternative until the brunch, we can take a few test shots at FAC using the rustic wooden tables we have downstairs. They'll need a bit of a clear up and would be a good starting point. 

We need 4 people for it, can we trial it tomorrow?

**Comment by hdrdavies** [comment]
@iteles Some non-loner images. Though they have been downloaded quite a lot... 

![image](https://cloud.githubusercontent.com/assets/13098199/12974294/c203573a-d0aa-11e5-8917-09acc3875bbb.png)

![image](https://cloud.githubusercontent.com/assets/13098199/12974305/c9810566-d0aa-11e5-9cac-383478c32f7a.png)

**Comment by hdrdavies** [comment]
And more! 

![image](https://cloud.githubusercontent.com/assets/13098199/12974363/3664d96e-d0ab-11e5-9554-f6f849da2daf.png)

![image](https://cloud.githubusercontent.com/assets/13098199/12974366/3c44ed42-d0ab-11e5-836c-138c299a6067.png)

**Comment by sohilpandya** [comment]
The first one isn't bad @hdrdavies, but I really do love the nevoed image. with all the charts! :8ball:

**Comment by tunnckoCore** [comment]
Hey guys, I found one awesome image.

![do-what-you-love_and_love-what-you-do](https://cloud.githubusercontent.com/assets/5038030/13725929/3972fd76-e8ba-11e5-9bb1-454eda07748b.jpg)

Cheers! :beer:

**Comment by iteles** [comment]
Thanks @tunnckoCore!
Is it this particular image or the concept of a cool landscape with this wording on it that you particularly like? :wink:

**Comment by tunnckoCore** [comment]
Yea, the wording, not so the landscape - I don't know where it is, but it is ugly, actually, haha.

**Comment by iteles** [comment]
:smile: :+1:

**Comment by iteles** [comment]
@sohilpandya We never got round to this! Must remember for the next dwyl lunch/dinner

**Comment by iteles** [comment]
Now on the website and superseded by #97! We want to roll our own :)
