### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl.github.io#99]
place to store images used on the site

![speed-dial](https://cloud.githubusercontent.com/assets/13098199/12919676/2cc96a6a-cf3d-11e5-952a-3903c0c8a240.png)
![smart-phone](https://cloud.githubusercontent.com/assets/13098199/12919679/2ee1b186-cf3d-11e5-81b3-224c5c7faba6.png)
![student](https://cloud.githubusercontent.com/assets/13098199/12919684/2ffa311a-cf3d-11e5-94b3-2eece3db6b2d.png)

Above are for #86 

To be credited like so: Mile by shimaru, Student by Berkay Sargın, Smartphone by João Proença - all from the Noun Project!

**Comment by iteles** [comment]
Is that a fuel gauge from a car? I ask because of my aversion to the oil industry... ;)

**Comment by hdrdavies** [comment]
oh no! Prefer a test tube? Ruler? @iteles

**Comment by iteles** [comment]
For user testing? Either a test tube or a notebook and pen, or a little person super-imposed infront of a computer where the computer screen shows a test tube? ;)

**Comment by hdrdavies** [comment]
![michelle](https://cloud.githubusercontent.com/assets/13098199/13013926/6f30bac0-d1a9-11e5-8eed-444690e57c94.jpg)
![simonl](https://cloud.githubusercontent.com/assets/13098199/13013927/6f310336-d1a9-11e5-8ad7-772232c811bf.jpg)
![rafe](https://cloud.githubusercontent.com/assets/13098199/13013928/6f44f1e8-d1a9-11e5-9a6a-1195a076d91f.jpg)
![nikhila](https://cloud.githubusercontent.com/assets/13098199/13013929/6f4a9db4-d1a9-11e5-9674-07392d066b99.jpg)
![nelson](https://cloud.githubusercontent.com/assets/13098199/13013930/6f4d082e-d1a9-11e5-88a2-9c29f5dccb10.jpg)
![naaz](https://cloud.githubusercontent.com/assets/13098199/13013931/6f4d6d50-d1a9-11e5-87a3-2835144daec3.jpg)
![mina](https://cloud.githubusercontent.com/assets/13098199/13013933/6f4fe698-d1a9-11e5-8c5d-67dcaa732dba.jpg)
![matt](https://cloud.githubusercontent.com/assets/13098199/13013932/6f4dfd38-d1a9-11e5-9605-420898e984f6.jpg)
![jackr](https://cloud.githubusercontent.com/assets/13098199/13013934/6f5bb068-d1a9-11e5-9d38-b56023f8a218.jpg)
![jackc](https://cloud.githubusercontent.com/assets/13098199/13013935/6f5e54a8-d1a9-11e5-88b9-4657798d4dc2.jpg)
![jack](https://cloud.githubusercontent.com/assets/13098199/13013937/6f605a64-d1a9-11e5-8fbe-2fd77621ab2e.jpg)
![ines](https://cloud.githubusercontent.com/assets/13098199/13013936/6f5f667c-d1a9-11e5-972e-a73bbf5e0e6a.jpg)
![huw](https://cloud.githubusercontent.com/assets/13098199/13013938/6f66121a-d1a9-11e5-8d3c-1c4baca79997.png)
![eoin](https://cloud.githubusercontent.com/assets/13098199/13013939/6f6aa834-d1a9-11e5-9863-e30bec69cef7.jpg)
![conor](https://cloud.githubusercontent.com/assets/13098199/13013940/6f6fd782-d1a9-11e5-8040-6434409eb2e2.jpg)
![anitac](https://cloud.githubusercontent.com/assets/13098199/13013941/6f7094ce-d1a9-11e5-8e3a-286e97ffe1b0.jpg)

**Comment by iteles** [comment]
Could we have these in an images folder please? Keeps everything a little more contained (check out  node-girls/node-girls-website) for how Nikki got this done 👍🏻

**Comment by hdrdavies** [comment]
Will do! Was going to keep them here in case I or Matt pushed them up on another computer...
